[package]
name = "substrate-consensus-babe-primitives"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Primitives for BABE consensus"
edition = "2018"

[dependencies]
substrate-client = { path = "../../../client", default-features = false }
rstd = { package = "sr-std", path = "../../../sr-std", default-features = false }
runtime_primitives = { package = "sr-primitives", path = "../../../sr-primitives", default-features = false }
substrate-primitives = { path = "../../../primitives", default-features = false }
slots = { package = "substrate-consensus-slots", path = "../../slots", optional = true }
consensus_accountable_safety_primitives = { package = "substrate-consensus-accountable-safety-primitives", path = "../../accountable-safety/primitives", default-features = false }
parity-codec = { version = "4.1.1", default-features = false }
schnorrkel = { version = "0.1.1", optional = true }

[features]
default = ["std"]
std = [
	"rstd/std",
	"runtime_primitives/std",
	"substrate-client/std",
	"parity-codec/std",
	"schnorrkel",
	"slots",
	"consensus_accountable_safety_primitives/std",
]
